PTJP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls')),
]

search/models.py
from django.db import models
import uuid

from western_cape.models import Arrival

# Create your models here.
class Search(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False, blank=False)
    start_stop = models.CharField(max_length=200, null=False, blank=False)
    end_stop = models.CharField(max_length=200, null=False, blank=False)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)

class Result(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False, blank=False, unique=True)
    title = models.CharField(default="",max_length=200, null=False, blank=False)
    result = models.ManyToManyField(Arrival)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"
      integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    {% block title %}{% endblock title %}

    <link
      rel="stylesheet"
      href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
      $(function () {
        var availableTags = [
          "BONTEHEUWEL A",
          "BONTEHEUWEL D",
          "LENTEGEUR A",
          "LENTEGEUR D",
          "MANDALAY A",
          "MANDALAY D",
          "ABBOTSDALE",
          "AKASIA PARK",
          "ARTOIS",
          "ATHLONE",
          "AVONDALE",
          "BELHAR",
          "BELLVILLE",
          "BELLVILLE A",
          "BELLVILLE D",
          "BLACKHEATH",
          "BONTEHEUWEL",
          "BOTHA",
          "BRACKENFELL",
          "BREE RIVER",
          "CAPE TOWN",
          "CENTURY CITY",
          "CHAVONNES",
          "CHRIS HANI",
          "CLAREMONT",
          "CRAWFORD",
          "DAL JOSAFAT",
          "DE GRENDEL",
          "DIEPRIVIER",
          "DU TOIT",
          "EERSTE RIVER A",
          "EERSTE RIVER D",
          "EIKENFONTEIN",
          "ELSIES RIVER",
          "ESPLANADE",
          "FALSE BAY",
          "FAURE",
          "FIRGROVE",
          "FISANTKRAAL",
          "FISH HOEK",
          "GLENCAIRN",
          "GOODWOOD",
          "GOUDA",
          "GOUDINI RD",
          "HARFIELD RD",
          "HAZENDAL",
          "HEATHFIELD",
          "HEIDEVELD",
          "HERMON",
          "HUGUENOT",
          "KALBASKRAAL",
          "KALK BAY",
          "KAPTEINSKLIP",
          "KENILWORTH",
          "KENTEMADE",
          "KHAYELITSHA",
          "KLAPMUTS",
          "KLIPHEUWEL",
          "KOEBERG RD",
          "KOELENHOF",
          "KRAAIFONTEIN",
          "KUILS RIVER",
          "KUYASA",
          "LAKESIDE",
          "LANGA",
          "LANSDOWNE",
          "LAVISTOWN",
          "LENTEGEUR",
          "LYNEDOCH",
          "MAITLAND",
          "MALAN",
          "MALMESBURY",
          "MANDALAY",
          "MBEKWENI",
          "MELLISH",
          "MELTONROSE",
          "MIKPUNT",
          "MITCHELLS PL.",
          "MONTE VISTA",
          "MOWBRAY",
          "MUIZENBERG",
          "MULDERSVLEI",
          "MUTUAL",
          "NDABENI",
          "NETREG",
          "NEWLANDS",
          "NOLUNGILE",
          "NONKQUBELA",
          "NYANGA",
          "OBSERVATORY",
          "OOSTERZEE",
          "OTTERY",
          "PAARDENEILAND",
          "PAARL",
          "PAROW",
          "PENTECH",
          "PHILIPPI",
          "PINELANDS",
          "PLUMSTEAD",
          "RETREAT",
          "ROMANS RIVER",
          "RONDEBOSCH",
          "ROSEBANK",
          "SALT RIVER",
          "SAREPTA",
          "SIMON`S TOWN",
          "SOETENDAL",
          "SOMERSET WEST",
          "SOUTHFIELD",
          "ST JAMES",
          "STEENBERG",
          "STELLENBOSCH",
          "STEURHOF",
          "STIKLAND",
          "STOCK ROAD",
          "STRAND",
          "SUNNY COVE",
          "THORNTON",
          "TULBAGHWEG",
          "TYGERBERG",
          "UNIBELL",
          "VAN DER STEL",
          "VASCO",
          "VLOTTENBURG",
          "VOELVLEI",
          "WELLINGTON",
          "WETTON",
          "WINTEVOGEL",
          "WITTEBOME",
          "WOLSELEY",
          "WOLTEMADE",
          "WOODSTOCK",
          "WORCESTER",
          "WYNBERG",
          "YSTERPLAAT",
        ];
        $("#id_start_stop").autocomplete({
          source: function (request, response) {
            var results = $.ui.autocomplete.filter(availableTags, request.term);
            response(results.slice(0, 5));
          },
        });
        $("#id_end_stop").autocomplete({
          source: function (request, response) {
            var results = $.ui.autocomplete.filter(availableTags, request.term);
            response(results.slice(0, 5));
          },
        });
      });
    </script>
  </head>
  <body>
    <header>
      <nav>
        <div class="logo">
          <h1><span class="hspn">Journey</span>Planner</h1>
          <i class="fa fa-train" aria-hidden="true"></i>
        </div>

        <a href="#" class="login-button">
          <i class="fa fa-user" aria-hidden="true"></i>
          <p>LOGIN OR SIGNUP</p>
        </a>
      </nav>

      <div class="form-wrapper">
        {% block searchform %} {% endblock searchform %}
      </div>
    </header>
    <main>{% block content %}{% endblock content %}</main>
  </body>

  <footer>
    <p>Designed and Developed by Talifhani</p>
  </footer>
</html>